### ISSUE TITLE
观鸟数据报错

### ISSUE THREAD

**Issue by wwwyyyhhh9** [Achernar0208/SpiderChaser#1]
跑的时候一直是这样的错误
285027 error
285054 error
285091 error
285299 error
285006 error
285010 error
285009 error
285012 error
请问是什么原因，有非常多行

**Comment by breezevv** [comment]
<img width="826" alt="image" src="https://github.com/Achernar0208/SpiderChaser/assets/84190507/7bc0b252-0cb7-489d-aca9-6ae3f10a3819">
修改一下这个地方哈
